apigee/microgateway-core

lib/plugins-middleware.js
tests/config.js
tests/config.yaml
tests/logging.test.js

Right now the `Host` header is always removed prior to making the target
request.  This commit allows you to alter the behavior using the
`config.headers.host` configuration.  The default value is `true`,
which means set (or reset) the `Host` header.  If set to `false`, it
means do not set (or reset) the `Host` header and the originally
requested `Host` header, if there is one, will be retained when making
the target request.

Allow retaining the original request Host header

---

lib/plugins-middleware.js

We were trying this at daimler and needed to disable the setting of the host from the client (was breaking ssl) and found this small error.
/geir

fixed a minor bug that caused host value to never work

---

lib/plugins-middleware.js

Prior to this change, if your query string had a `//` in it, it would be
replaced with a `/` when generating the proxy target path.  This change
keeps the code in place but makes the string replacement only happen for
the path and not the query string.

stop replacing double slashes in the query string

---

lib/plugins-middleware.js

Date.now wasn't being used as a function.

Fixing bug in lib/plugins-middleware.js that mangles the x-response-time header.

---

package.json

microgateway-core currently has a vulnerable dependency, introducing [ReDOS vulnerability](https://snyk.io/vuln/npm:tough-cookie:20160722) in the `tough-cookie` dependency.
You can see [Snyk test report](https://snyk.io/test/github/apigee/microgateway-core) of this project for details. 
This PR changes `Package.json` to upgrade `request` to the newer 2.74.0 version, which uses the fixed `tough-cookie` version 2.3.1, and does not pull in any other vulnerable dependencies.
You can get alerts and fix PRs for future vulnerabilities for free by [watching this repo with Snyk](https://snyk.io/add).
Stay Secure,
The Snyk Community.

Fix for  vulnerable dependency path.

---

lib/config-proxy-middleware.js
lib/plugins-middleware.js

First pass at the header functionality.

Adding functionality to set custom headers, and unset headers in plugins.

---

lib/plugins-middleware.js

Fixes a regression where keep-alive isn't used properly. 
See community post.
https://community.apigee.com/questions/34813/http-keepalive-connections-from-edgemicro-to-targe.html

Use the agent as defined in proxy-middleware.js so we can have keep-alive logic.

---

lib/plugins-middleware.js
tests/plugins-behavior.js

This is a potential fix for issues where plugins would like access to the targetResponse.

Makes plugin type detection clearer. Provides the targetResponse as an argument.

---

lib/ondata-transform.js
lib/plugins-middleware.js
tests/plugin-lifecycle.js
tests/plugins-behavior.js
tests/testPlugin.js

use native node streams/piping instead of hacking around with promises.  The previous implementation represented a memory leak during the duration of large requests.  This fixes that, and simplifies the core middleware logic.

fixing memory leak which occurs during large request/responses

---

lib/plugins-middleware.js
tests/request-timeout-tests.js

Adding a way to configure timeout functionality for target requests. Along with tests for it.

---

lib/logging.js

This is a small change to allow microgateway to properly report log file path. It'll also report the new log file path every time there is a rotation.

Update to allow for reporting the proper log output file.

---

lib/plugins-middleware.js
tests/response-status-message-tests.js

https://community.apigee.com/questions/37253/edge-microgateway-is-not-returning-the-reason-phra.html
Edgemicro wasn't allowing custom status messages from target responses to be sent back to the source response. This fixes that issue.

Response status message

---

lib/plugins-middleware.js

Previously it would check length, but if null was passed this would cause an error, and append it to the response body.

Does a better check on result argument passed to onend callbacks. 

---

lib/plugins-middleware.js
tests/request-timeout-tests.js

Two things in this pull request.
Setting the `timeout` option on the request doesn't really do what I thought it did. It sets the timeout on the underlying socket to fire a `"timeout"` event that requires interception. In that handler the user is supposed to kill the connection of the underlying socket.
This pull request does a few things:
- Fixes two bad tests that were giving bad gateway errors for the wrong reasons. 
- One test will look for a 504 indicating the gateway timed out waiting to hear from a target
- One test will ensure that hearing from the target before the timeout is set doesn't affect the request / response pipeline
- We move from setting the `timeout` option in the options object for the request to using `setTimeout` which will actually fire a callback when the timeout …

Updates to the request timeout handling logic to actually abort the request.

---

lib/config-proxy-middleware.js

Hello
EMG doc specifies:
> This example provides settings that will be applied to all hosts:
```
targets:
ssl:
client:
key: /Users/jdoe/nodecellar/twowayssl/ssl/client.key
cert: /Users/jdoe/nodecellar/twowayssl/ssl/ca.crt
passphrase: admin123
rejectUnauthorized: true
```
This setting without host does not work: the function passed to `filter()` does not check if host is not specified.
This commit fixes this problem.
All the best

fix 2-way ssl setting to be applied to all targets

---

lib/build-non-tunnel-options.js
lib/build-tunnel-agent.js
lib/config-proxy-middleware.js
lib/config.js
lib/plugins-middleware.js
package.json
tests/proxy-options-tests.js
tests/proxy-tests-tls.js
tests/proxy-tests.js

WIP
This is to implement proxying support for the following configuration options in microgateway.
```yaml
edge_config:
proxy: http://10.224.16.85:3128
proxy_tunnel: false
```
Also will build in support for the `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy`, and `https_proxy` environment variables.
This will allow a user to set these specific variables, or configuration to have edgemicro route it's http traffic through a proxy server. This is currently half supported in retrieving configuration, but in the actual API message processing it isn't supported.
We're using a similar approach to the `request` module, and a library they produced for http tunneling called `tunnel-agent`. This will allow us to use connect tunneling, or putting a full URL in the path of a request.
Task list and marked if …

Proxy support

---

lib/plugins-middleware.js

Solves issue where stream was not finished processing data, but we were executing end handlers anyway. This causes a partial response to be sent.

Fix for streaming issues, by leaving stream open.

---

lib/gateway.js
package.json

While the Apigee Microgateway provides support for bidirectional ssl between itself and the target, there is no support for bidirectional ssl between the source and itself.
I believe that this might have been the intention of a previous commit because part of the options for the https server include `rejectUnauthorized: config.edgemicro.ssl.rejectUnauthorized`. However, according the the Node.js documentation, this option has no effect unless the requestCert option is true. This option is not currently specified in the options. Hence I am adding it.

fixing bi-directional ssl support from source

---

lib/config-proxy-middleware.js
lib/config.js
lib/no-proxy-parser.js
lib/plugins-middleware.js
tests/no-proxy-parser-tests.js
tests/proxy-tests.js

The proxy server implementation must respect the NO_PROXY variable to override the HTTP_PROXY or HTTPS_PROXY variables.

We need to respect the no_proxy environment variable.

---

README.md

I added three strategically-placed spaces.
I also capitalized things, because I like to use the full range of ASCII characters outside of password requirements.

Fix readme's markdown

---

lib/no-proxy-parser.js
npm-shrinkwrap.json
package.json
tests/no-proxy-parser-tests.js

We have a client that is using PCF and PCF allows developers to create new URLs for each app that they create.   The current implementation of Edge Microgateway requires users to explicitly list all domains in the NO_PROXY environment variable (i.e. NO_PROXY=app1.pcf.domain.com, app2.pcf.domain.com,app3.pcf.domain.com).
This is a significant burden on PCF developers using Edge Microgateway.  The solutions is to allow a wildcard (*) parameter in the domains listed in the NO_PROXY environment variable.  
This pull requests allows developers to use * as a wildcard in the NO_PROXY environment variable.
For example:
foo.com:4000 **matches** no_proxy: foo.com
foo.com:4000 **matches** no_proxy: foo.com:4000
foo.com:4000 **does not match** no_proxy: foo.com:3000
foo.bar.com:4000 **matches** …

Microgateway does not accept NO_PROXY=*.domain.com

---

lib/plugins-middleware.js

b127687184
Adds support for targets accepting content-length only. 
1. edgemicro.contentlength is used if the content-length is supplied and body is not transformed
2. plugins - contentlength is used if the body is transformed
edgemicro:
contentlength: true
plugins:
sequence:
- oauth
- contentlength

add content-length setting

---

lib/logging.js

The writeLogRecord function of logger is expecting object with 'msg' as string to be logged in fle.
So if just string is passed to writeLogRecord then it is ignored.

Passing object instead of String

---

lib/logging.js

Use node library 'util' to add printf-like format to console logs.

Add format to console logs

---

lib/gateway.js
tests/config.yaml

This solves an error where a load balancer will try to use a connection
that node has closed. In GCP, this erorr shows up in the logs as:
backend_connection_closed_before_data_sent_to_client
Google's documentation states that their keepalive time is set to 10mins
and to try setting your server time to greater than that. This enables
microgateway to set that (beyond the 5sec default) and be configurable
based on a clients needs.
Details:
https://blog.percy.io/tuning-nginx-behind-google-cloud-platform-http-s-load-balancer-305982ddb340
https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring

Add configurable keepAliveTimeout

---

lib/plugins-middleware.js

Update logs in plugins middleware to correct the latency value to match with the analytics data.
Change log level of 'sourceRequest','targetRequest' and 'targetResponse' to 'info'.

For310 logging changes

---

lib/logging.js

Add null check on 'req.agent.sockets[0]' while reading hostname from request object to
print in event log.

Add error handling to logger

---

lib/gateway.js

Set Header 'Connection: close' on source request when server is not listening.

151284716 close conn when server is not listening

---

lib/config-proxy-middleware.js
lib/config.js
lib/plugins-middleware.js
lib/plugins.js
tests/proxy-tests-tls.js
tests/proxy-tests.js

Separated proxy server configs for edge and target calls.
For edge calls:
Use only environment variables HTTP_PROXY/http_proxy or HTTPS_PROXY/https_proxy to use a proxy server for calls to edge.
Previous configs edge_config.proxy and edge_config.proxy_tunnel are no longer applicable.
For target calls:
Add proxy configs to 'edgemicro' section to proxy the target calls. Below is an example:
edgemicro:
proxy:
tunnel: true
url: 'http://192.168.2.178:3128'
bypass: 'localhost' # target hosts to bypass the proxy.
enabled: true
If edgemiro.proxy.enabled is 'true' and proxy.url is not set,
env variables HTTP_PROXY/http_proxy and HTTPS_PROXY/https_proxy will be used.
If edgemicro.proxy.enabled is set 'true' but no url or env variables HTTP_PROXY is defined,
Edgemicro will fail to start with assert …

151285018 Add proxy configs in edgemicro

---

lib/plugins-middleware.js

Change log level from 'error' to 'info' for 'targetResponse closed' log.

149101890 Correct log level

---

lib/plugins.js

Pass 'config.edgemicro.global' to the quota plugin subconfig.
The 'config.edgemicro.global' has org and env values.

152005003 Pass org and env to quota plugin

---

lib/plugins-middleware.js

Add sendMetricsData function for sending metrics plugin data to the master node.
Update plugins sequence to enable 'metrics' plugin after 'analytics' in both preflow and postflow.

Send metrics data.

---

lib/logging.js
lib/plugins-middleware.js
tests/target-behavior.js

Add target hostname in 'transactionContextData' and use that to correctly print target hostname in event logs.

155077210 Correctly print target hostname in logs

---

lib/PluginsSeqManager.js
lib/gateway.js
lib/plugins-middleware.js

Apply only default plugins if 'request url' is present in global excludeUrls.
Skip the plugins whose excludeUrls includes the 'request url'.
Disable caching if 'disableExcUrlsCache' is set to 'true'.
A sample config is:
plugins:
excludeUrls: '/hello,/hello/'
disableExcUrlsCache: true
sequence:
- oauth ## used for apikey verification #
- json2xml
json2xml:
excludeUrls: '/hello/help'

Add excludeUrls feature

---

lib/plugins-middleware.js

Register the source response close event when target request is sent instead of registering after response is started to stream from target.

Handle source response close event correctly

---

lib/PluginsSeqManager.js
lib/plugins-middleware.js

Calculate preflow plugin sequence and postflow plugin sequence in PluginsSeqManager.
Set 'preflowPluginSequence' and 'postflowPluginSequence' on 'sourceRequest' object.
Use 'sourceRequest.preflowPluginSequence' and 'sourceRequest.postflowPluginSequence' in plugins-middleware.

Tag plugins sequence to request object

---

lib/plugins-middleware.js

Updated the Source Request ‘on end’ event to ‘on data transform’ request’s ‘on end’ to avoid premature ending of source stream.
This will fix the ‘ERR_STREAM_WRITE_AFTER_END’ error and data truncation issue in request payload, for large dataset requests.

 173064680 Fix the data truncation issue

---

lib/plugins-middleware.js

Set 'target_response_code' property on req object because analytics plugin needs this data

179971737 Capture target status code in analytics

---

lib/plugins-middleware.js

Added request header ‘transfer-encoding’ with value as ‘chunked’ for source request method as GET
Set ‘_hasBody’ property of target request to allow body for ‘GET method requests’

179366445 Add support for GET requests with body

---

lib/plugins-middleware.js

Added consideration for new config variable 'enable_GET_req_body' which is optional
Set request header ‘transfer-encoding’ with value as ‘chunked’ only if with source request method as GET the config enable_GET_req_body is also specified with value as true
Set ‘_hasBody’ property of target request to true  to allow body(for GET requests) only if with request method as GET the config enable_GET_req_body is also specified with value as true

179366445 Make support for GET requests with body configurable

---

lib/logging.js

Optimised code to support new config “disableStrictLogFile” to change the permission of log file.
Permission of the log file will be set to 0755 if “disableStrictLogFile” config is set to true.
Default value will be the same as earlier that is 0600 if the config is not mentioned or set to anything other than true.

192416584 Make permissions for log file configurable

---

lib/plugins-middleware.js
tests/proxy-tests.js

Change log level to from 'warn' to 'error' on target request 'error' event log
Add test cases to verify response behaviour in case of target request error

138414116 Add test case for target request error

---

lib/plugins-middleware.js
package.json

Added condition to check if the source request is aborted and
update the status code for response, event logs and analytics with
HTTP status code 499 if the request is aborted at any given point.

192534424 Fix the status code when request is aborted
