apigee/microgateway-core

lib/plugins.js

mostly taken from microgateway-core/server.js which seems to be unused?

pass proxy configuration along to plugins

---

lib/config-proxy-middleware.js
lib/config.js
lib/plugins-middleware.js

Add to the config file:
```yaml
targets:
- host: 'zetta-cloud-2.herokuapp.com'
ssl:
client:
key: "/Users/kevin/Downloads/ca.key"
cert: "/Users/kevin/Downloads/ca.crt"
```

Client SSL options

---

README.md

Fixes code in the README. It wasn't a sample that was working properly.

Fixing the README sample to highlight proper usage.

---

lib/plugins-middleware.js

Fix for an issue where plugins that transform API response

---

lib/gateway.js

Adding passphrase as a config option for edgemicro ssl.

---

lib/config-proxy-middleware.js
lib/plugins-middleware.js
tests/plugin-lifecycle.js
tests/testPlugin.js

Improve the way that plugin authors can modify the request url.  Currently, it's pretty bad -> https://community.apigee.com/questions/15825/how-to-override-default-url-on-edge-micro-gateway.html

initial fix for rewriting target URLs

---

lib/logging.js
lib/plugins-middleware.js

Updates to send logging directly to std out.

Logging update

---

lib/config-proxy-middleware.js
lib/plugins-middleware.js

Attaching an agent to a proxy to prevent multiple instantiations.

Stress testing

---

lib/plugins-middleware.js

Reverse plugin execution order per the documentation.

---

lib/plugins-middleware.js
tests/forwarded-header-tests.js

Add support for x-forwarded-proto header

---

lib/config-proxy-middleware.js
lib/proxy-path-matcher.js
tests/config_target_ssl.js
tests/path-matching-tests.js
tests/proxy-tests-tls.js

Starting to work on wildcard path matching.

---

lib/gateway.js
lib/plugins-middleware.js
npm-shrinkwrap.json
package.json

set the server timeout to max. the target timeout will ensure the server does not indefinitely wait.

set server timeout to max

---

tests/config-tests.js
tests/config_target_ssl.js
tests/proxy-tests-tls.js
tests/proxy-tests.js
tests/response-status-message-tests.js

Changes for a message in tests.

Changes for a message in tests.

---

lib/errors-middleware.js
lib/gateway.js
lib/logging.js
lib/plugins-middleware.js

Log improvements

---

index.js
lib/gateway.js
lib/logging.js
lib/ondata-transform.js
lib/plugins-middleware.js
lib/plugins.js
server.js

Creating centralized console logging.

Loggers improvements phase 2

---

lib/logging.js

Print error stack to log file if stack_trace is set to true.

for306 138722809 print error stack if stack_trace true

---

lib/logging.js

add process id(worker id) to system logs

140090250 add process id to logs

---

lib/config-proxy-middleware.js
lib/plugins-middleware.js

Override default timeout by proxy level timeout if set.

Fix bug 142496489 and add proxy level timeout

---

lib/gateway.js

Configure and set config.edgemicro.headers_timeout value in server.headersTimeout.

Configure config.edgemicro.headers_timeout in config.yaml

---

lib/config.js
lib/plugins.js

Remove check on NO_PROXY while reading env variables

Fix bug 146069701

---

lib/logging.js
lib/plugins-middleware.js

Set transactionContextData on sourceRequest object instead of logger.

Correctly set transactionContextData

---

index.js
lib/admin-server.js

Start admin server on port = edgemicro.port + 1.
Collect and process the records sent by 'metrics' plugin.
Expose below end points:
1. /stats : This will return the KPIs of all the proxies.
2. /stats/<ProxyName> : This returns data of specified proxy.
Clear the data of poxies whose ( last usage time + grace period ) is less than current time.
Reset proxy values if any one value in proxy reaches to max allowed numeric value.

Add Admin server

---

lib/plugins-middleware.js

Add null check for targetResponse.statusCode

Add null check.

---

lib/admin-server.js
lib/plugins-middleware.js

If isRolloverAll is set to true then rollover all values when atleast one value rollovers.

Make rollover configurable

---

lib/logging.js

Add exception handling to logger when creating a log file.

153949764 Add Exception handling to logger

---

index.js
lib/plugins.js

Pass emg level configs to plugin's subconfig under key 'emgConfigs'.

160431789 pass emg config to plugins

---

lib/proxy-path-matcher.js

Correct the path matcher to block invalid base paths.

161092943 Correct path matcher

---

lib/plugins.js

Pass 'getRedisClient' function to quota plugin subconfig

158618994 Pass redis client to quota plugin

---

lib/plugins-middleware.js

End the target request writer manually after the onend_request event

166356972 End the writer correctly

---

lib/errors-middleware.js

Add try/catch to handle the parsing issue.
Remove invalid southbound certificat from err object.

141659881 JSON parsing error.

---

lib/plugins-middleware.js

Fix the onerror_response event issue for all plugin

159571119 Fix onerror event for request and response of plugins

---

lib/errors-middleware.js

Check if response is already finished before writing the error message on response

176462872 Add error handling for Node Js 14

---

lib/plugins-middleware.js

Added logger in the pluginhook event flow and sourceRequest flow for debugging issue in the request during and after reload

190715670 Add logger for identifying cause of API failing post reload

---

lib/plugins-middleware.js

Added condition to handle aborted target response
Made target response behaviour configurable by adding a config target_response_on_abort

192799989 Handle premature ending of target response

---

tests/proxy-tests.js
tests/target-behavior.js

fixed npm test issues in core module
replaced match method of assert with ok for backward compatibility

213825005 Fix npm test issues
